# Stark Accessibility Audit
# https://aka.ms/yaml

trigger:
  # See https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/trigger?view=azure-pipelines for more information.
  - none

pool:
  vmImage: ubuntu-latest

steps:
  # This is where you execute the commands needed to build and run your server locally in the background.
  # NOTE: the '&' at the end of the 'npm run dev &' command is needed to ensure the pipeline can continue to the next step.
  - script: |
      npm i
      npm run dev &
    displayName: 'Build and run server'

  # This is where you configure your Stark Accessibility Audit.
  - task: StarkAccessibilityAudit@1
    env:
        STARK_REPORT_URL: https://dh-stark.ngrok.dev/api/cli-webhooks/scan-result/:scanId
        STARK_COMPLETION_URL: https://dh-stark.ngrok.dev/api/cli-webhooks/end-scan/:scanId
        STARK_DETAILS_URL: https://dh-stark.ngrok.dev/api/cli-webhooks/scan-details/:scanId
    inputs:
        # [Required] The Stark token provided when you created your project on the Stark web app.
        # Example: 'stark_705199c1bfc34311b616c92b0748f4d0'
        token: 'stark_bebc406722324ebdab2d19e0244fd86b'
            
        # [Required] A list of URLs to be scanned, with each URL on its own line.
        # This value follows YAML conventions for multiline strings.
        # NOTE: This is the likely the only value you have to change!
        urls: |
            http://localhost:3000