# Stark Accessibility Audit
# https://aka.ms/yaml

trigger:
  # This pipeline must be triggered from within the Stark web application to function properly.
  - none

pool:
  vmImage: ubuntu-latest

steps:
  # This is where you execute the commands needed to build and run your server locally in the background.
  # NOTE: the '&' at the end of the 'npm run dev &' command is needed to ensure the pipeline can continue to the next step.
  - script: |
      npm i
      npm run dev &
    displayName: 'Build and run server'

  # This is where you configure your Stark Accessibility Audit.
  - task: StarkAccessibilityAudit@1
    env:
      STARK_REPORT_URL: https://dh-stark.ngrok.dev/api/cli-webhooks/scan-result/:scanId
      STARK_COMPLETION_URL: https://dh-stark.ngrok.dev/api/cli-webhooks/end-scan/:scanId
    inputs:
      # [Required] This predefined value will use the token Stark provides when starting the pipeline.
      token: 'stark_54d8f790f03945cc95267993cfafdbe7'

      # [Required] A list of URLs to be scanned, with each URL on its own line.
      # This value follows YAML conventions for multiline strings.
      # NOTE: This is the likely the only value you have to change!
      urls: |
        http://localhost:3000
