# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: token
  value: <provided by Stark>

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: StarkAccessibilityAudit@0
  inputs:
    token: $(token)
