# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: token
  displayName: Stark token
  type: string

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'
- task: UseNode@1
  inputs:
    version: '20.x'
- task: StarkAccessibilityAudit@0
  inputs:
    token: ${{ parameters.token }}
