# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: token
  displayName: Stark token
  type: string

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: './accessibility-audit/Dockerfile'
    arguments: '-t auditor-image'
    addPipelineData: false
- task: Docker@2
  inputs:
    command: 'start'
    arguments: '-it --rm'
    addPipelineData: false
    container: 'auditor-image'