# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: token
  displayName: Stark Token (provided by Stark)
  default: 
  type: string

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo 'This is where we would install npm, get the accessibility-cli, etc.'
    echo 'token =' ${{ parameters.token }}
  displayName: 'Set up Stark CLI'
- task: Stark-Contrast.accessibility-audit-task@1
  inputs:
    token: 'token1234'
